### PR TITLE
fix(short-order-id): update example

### PR DESCRIPTION
**Pull request by ArtyomResh**

### CODE REVIEW

**Review by notrab — CHANGES_REQUESTED** [review]
Thanks for the PR

Can I ask what the intentions were to replace the request library with the js-sdk?

Also, can you run prettier on these. I’ll make it a priority to add this as a commit hook.

**Comment by ArtyomResh** [comment]
> Can I ask what the intentions were to replace the request library with the js-sdk?

This library is less popular than `@moltin/sdk`. I thought it would be more likely that people who use `@moltin/sdk` would turn to this example more often.

> Also, can you run prettier on these. I’ll make it a priority to add this as a commit hook.

Sure, but I will do it later

**Comment by notrab** [comment]
Ah ok. The request library is relatively new and hugely popular with those just touching fewer endpoints. 

I’d like to revert the SDK changes in this PR as the full SDK brings a lot of unnecessary weight.

**Comment by ArtyomResh** [comment]
> Ah ok. The request library is relatively new and hugely popular with those just touching fewer endpoints.
> 
> I’d like to revert the SDK changes in this PR as the full SDK brings a lot of unnecessary weight.

Oh, I understand, okay 👌

**Pull request closed without merging**
